// Auto-generated by tools/gen_mister_profiles.py from BrickEmuPy's
// .brick configs. Do not hand-edit — rerun the generator instead.

localparam int NUM_PROFILES = 4;

localparam int          PROFILE_CLK_DIV[4]  = '{49, 194, 97, 52};
localparam logic [15:0] PROFILE_TIMER_DIV[4] = '{16, 16, 8, 16};
localparam logic [15:0] PROFILE_SOUND_FREQ_DIV[4] = '{64, 32, 32, 64};

localparam logic [3:0] PROFILE_PP_WAKEUP[4] = '{0, 0, 0, 2};
localparam logic [3:0] PROFILE_PM_WAKEUP[4] = '{0, 0, 0, 0};
localparam logic [3:0] PROFILE_PS_WAKEUP[4] = '{4, 1, 1, 0};

localparam logic [11:0] PROFILE_RESET_JMAP[4] = '{0, 512, 512, 0};

localparam logic [11:0] PROFILE_PP_JMAP[4][4] = '{'{16, 4, 1, 2}, '{1, 2, 0, 0}, '{0, 0, 0, 0}, '{256, 128, 64, 16}};
localparam logic [11:0] PROFILE_PM_JMAP[4][4] = '{'{0, 0, 0, 0}, '{0, 0, 0, 0}, '{48, 4, 65, 2}, '{0, 0, 0, 0}};
localparam logic [11:0] PROFILE_PS_JMAP[4][4] = '{'{32, 64, 128, 0}, '{160, 64, 256, 128}, '{384, 0, 0, 0}, '{2, 1, 4, 0}};

localparam logic [7:0] PROFILE_SPD[4][16] = '{'{7, 41, 103, 31, 63, 63, 109, 31, 123, 119, 1, 37, 17, 114, 11, 11}, '{29, 125, 59, 17, 83, 60, 37, 100, 127, 117, 127, 127, 54, 14, 91, 127}, '{7, 41, 103, 31, 63, 63, 41, 31, 123, 84, 1, 37, 17, 10, 11, 11}, '{92, 32, 32, 1, 76, 76, 41, 41, 7, 1, 1, 1, 1, 1, 1, 1}};
localparam logic [7:0] PROFILE_FX[4][16] = '{'{0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0}, '{0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 7, 7, 0, 0, 0, 7}, '{0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0}, '{0, 0, 0, 6, 0, 1, 1, 1, 0, 7, 7, 7, 7, 7, 7, 7}};

